"""Type stubs for the native extension module."""

from typing import Any

HashInput = bytes | str

class AgcliError(Exception):
    code: int
    hint: str | None

class NetworkError(AgcliError): ...
class AuthError(AgcliError): ...
class ValidationError(AgcliError): ...
class ChainError(AgcliError): ...
class TimeoutError(AgcliError): ...
class IOError(AgcliError): ...

class Balance:
    def __init__(self, *, rao: int | None = None, tao: float | None = None) -> None: ...
    @staticmethod
    def from_rao(rao: int) -> Balance: ...
    @staticmethod
    def from_tao(tao: float) -> Balance: ...
    @property
    def rao(self) -> int: ...
    @property
    def tao(self) -> float: ...

class AlphaBalance:
    def __init__(self, value: Any) -> None: ...
    @property
    def raw(self) -> int: ...
    @property
    def rao(self) -> int: ...
    @property
    def tao(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

class NetUid:
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...

class Network:
    @staticmethod
    def finney() -> Network: ...
    @staticmethod
    def test() -> Network: ...
    @staticmethod
    def local() -> Network: ...
    @staticmethod
    def archive() -> Network: ...
    @staticmethod
    def custom(url: str) -> Network: ...
    @staticmethod
    def parse(name: str) -> Network: ...
    @property
    def ws_url(self) -> str: ...

class _TypedSerde:
    def __init__(self, value: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class SubnetInfo(_TypedSerde): ...
class NeuronInfo(_TypedSerde): ...
class NeuronInfoLite(_TypedSerde): ...
class Metagraph(_TypedSerde): ...
class StakeInfo(_TypedSerde): ...
class DelegateInfo(_TypedSerde): ...
class DynamicInfo(_TypedSerde): ...
class SubnetHyperparameters(_TypedSerde): ...
class ChainIdentity(_TypedSerde): ...
class SubnetIdentity(_TypedSerde): ...

class Config:
    network: str | None
    endpoint: str | None
    wallet_dir: str | None
    wallet: str | None
    hotkey: str | None
    output: str | None
    proxy: str | None
    live_interval: int | None
    batch: bool | None
    spending_limits: dict[str, float] | None
    finalization_timeout: int | None
    mortality_blocks: int | None
    def __init__(
        self,
        network: str | None = None,
        endpoint: str | None = None,
        wallet_dir: str | None = None,
        wallet: str | None = None,
        hotkey: str | None = None,
        output: str | None = None,
        proxy: str | None = None,
        live_interval: int | None = None,
        batch: bool | None = None,
        spending_limits: dict[str, float] | None = None,
        finalization_timeout: int | None = None,
        mortality_blocks: int | None = None,
    ) -> None: ...
    @staticmethod
    def load() -> Config: ...
    @staticmethod
    def load_from(path: str) -> Config: ...
    @staticmethod
    def default_path() -> str: ...
    def save(self) -> None: ...
    def save_to(self, path: str) -> None: ...

class Client:
    @staticmethod
    async def connect(url: str) -> Client: ...
    @staticmethod
    async def connect_with_retry(urls: list[str]) -> Client: ...
    @staticmethod
    async def best_connection(urls: list[str]) -> Client: ...
    @staticmethod
    async def connect_network(network: Network | None = None) -> Client: ...
    @staticmethod
    async def from_config() -> Client: ...
    @property
    def endpoint(self) -> str: ...
    @property
    def network(self) -> Network: ...
    def set_dry_run(self, enabled: bool) -> None: ...
    def is_dry_run(self) -> bool: ...
    def set_finalization_timeout(self, timeout: int) -> None: ...
    def finalization_timeout(self) -> int: ...
    def set_mortality_blocks(self, blocks: int) -> None: ...
    def mortality_blocks(self) -> int: ...
    async def reconnect(self) -> None: ...
    async def is_alive(self) -> bool: ...
    async def invalidate_cache(self) -> None: ...
    async def get_balance(self, address: str) -> Balance: ...
    async def get_balance_at_hash(self, address: str, block_hash: HashInput) -> Balance: ...
    async def get_balance_at_block(self, address: str, block_number: int) -> Balance: ...
    async def get_balances_multi(self, addresses: list[str]) -> list[tuple[str, dict[str, Any]]]: ...
    async def get_block_hash(self, block_number: int) -> str: ...
    async def get_block_number(self) -> int: ...
    async def get_finalized_block_number(self) -> int: ...
    async def pin_latest_block(self) -> str: ...
    async def get_total_stake_at_block(self, block_number: int) -> Balance: ...
    async def get_block_header(self, block_hash: HashInput) -> tuple[int, str, str, str]: ...
    async def get_block_extrinsic_count(self, block_hash: HashInput) -> int: ...
    async def get_block_timestamp(self, block_hash: HashInput) -> int | None: ...
    async def get_total_issuance(self) -> Balance: ...
    async def get_total_stake(self) -> Balance: ...
    async def get_total_networks(self) -> int: ...
    async def get_block_emission(self) -> Balance: ...
    async def get_subnet_registration_cost(self) -> Balance: ...
    async def get_network_overview(self) -> tuple[int, dict[str, Any], int, dict[str, Any], dict[str, Any]]: ...
    async def get_total_issuance_at(self, block_hash: HashInput) -> Balance: ...
    async def get_total_stake_at(self, block_hash: HashInput) -> Balance: ...
    async def get_total_networks_at(self, block_hash: HashInput) -> int: ...
    async def get_block_emission_at(self, block_hash: HashInput) -> Balance: ...
    async def get_block_number_at(self, block_hash: HashInput) -> int: ...
    async def get_all_subnets(self) -> list[dict[str, Any]]: ...
    async def get_subnet_info(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_subnet_hyperparams(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_dynamic_info(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_all_dynamic_info(self) -> list[dict[str, Any]]: ...
    async def get_metagraph(self, netuid: NetUid | int) -> dict[str, Any]: ...
    async def get_neuron(self, netuid: NetUid | int, uid: int) -> dict[str, Any] | None: ...
    async def get_neurons_lite(self, netuid: NetUid | int) -> list[dict[str, Any]]: ...
    async def get_stake_for_coldkey(self, coldkey: str) -> list[dict[str, Any]]: ...
    async def get_delegates(self) -> list[dict[str, Any]]: ...
    async def get_delegate(self, hotkey: str) -> dict[str, Any] | None: ...
    async def get_identity(self, ss58: str) -> dict[str, Any] | None: ...
    async def get_subnet_identity(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_subnet_info_pinned(self, netuid: NetUid | int, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def get_subnet_hyperparams_pinned(self, netuid: NetUid | int, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def get_identity_pinned(self, ss58: str, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def get_subnet_identity_pinned(self, netuid: NetUid | int, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def get_delegate_pinned(self, hotkey: str, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def list_proxies_pinned(self, ss58: str, block_hash: HashInput) -> list[tuple[str, str, int]]: ...
    async def get_coldkey_swap_scheduled_pinned(self, ss58: str, block_hash: HashInput) -> tuple[int, str] | None: ...
    async def get_child_keys_pinned(self, hotkey_ss58: str, netuid: NetUid | int, block_hash: HashInput) -> list[tuple[int, str]]: ...
    async def get_pending_child_keys_pinned(self, hotkey_ss58: str, netuid: NetUid | int, block_hash: HashInput) -> tuple[list[tuple[int, str]], int] | None: ...
    async def get_stake_for_coldkey_pinned(self, coldkey: str, block_hash: HashInput) -> list[dict[str, Any]]: ...
    async def get_stake_for_coldkey_at_block(self, coldkey: str, block_number: int) -> list[dict[str, Any]]: ...
    async def get_identity_at_block(self, ss58: str, block_number: int) -> dict[str, Any] | None: ...
    async def get_all_subnets_at_block(self, block_number: int) -> list[dict[str, Any]]: ...
    async def get_all_dynamic_info_at_block(self, block_number: int) -> list[dict[str, Any]]: ...
    async def get_dynamic_info_at_block(self, netuid: NetUid | int, block_number: int) -> dict[str, Any] | None: ...
    async def get_neurons_lite_at_block(self, netuid: NetUid | int, block_number: int) -> list[dict[str, Any]]: ...
    async def get_neuron_at_block(self, netuid: NetUid | int, uid: int, block_number: int) -> dict[str, Any] | None: ...
    async def get_delegates_at_block(self, block_number: int) -> list[dict[str, Any]]: ...
    async def get_total_issuance_at_block(self, block_number: int) -> Balance: ...
    async def list_proxies(self, ss58: str) -> list[tuple[str, str, int]]: ...
    async def list_multisig_pending(self, multisig_ss58: str) -> list[tuple[str, int, int, int, int]]: ...
    async def list_proxy_announcements(self, ss58: str) -> list[tuple[str, str, int]]: ...
    async def get_coldkey_swap_scheduled(self, ss58: str) -> tuple[int, str] | None: ...
    async def get_child_keys(self, hotkey_ss58: str, netuid: NetUid | int) -> list[tuple[int, str]]: ...
    async def get_parent_keys(self, hotkey_ss58: str, netuid: NetUid | int) -> list[tuple[int, str]]: ...
    async def get_pending_child_keys(self, hotkey_ss58: str, netuid: NetUid | int) -> tuple[list[tuple[int, str]], int] | None: ...
    async def get_delegated(self, hotkey_ss58: str) -> list[dict[str, Any]]: ...
    async def get_weight_commits(self, netuid: NetUid | int, hotkey_ss58: str) -> list[tuple[str, int, int, int]] | None: ...
    async def get_all_weight_commits(self, netuid: NetUid | int) -> list[tuple[str, list[tuple[str, int, int, int]]]]: ...
    async def get_reveal_period_epochs(self, netuid: NetUid | int) -> int: ...
    async def get_weights_for_uid(self, netuid: NetUid | int, uid: int) -> list[tuple[int, int]]: ...
    async def get_all_weights(self, netuid: NetUid | int) -> list[tuple[int, list[tuple[int, int]]]]: ...
    async def get_commit_reveal_weights_version(self) -> int: ...
    async def get_commitment(self, netuid: int, hotkey_ss58: str) -> tuple[int, list[str]] | None: ...
    async def get_all_commitments(self, netuid: int) -> list[tuple[str, int, list[str]]]: ...
    async def get_block_info_for_pow(self) -> tuple[int, str]: ...
    async def get_difficulty(self, netuid: NetUid | int) -> int: ...
    async def fetch_portfolio(self, coldkey_ss58: str) -> dict[str, Any]: ...

class ClientSync:
    @staticmethod
    def connect(url: str) -> ClientSync: ...
    @staticmethod
    def connect_with_retry(urls: list[str]) -> ClientSync: ...
    @staticmethod
    def best_connection(urls: list[str]) -> ClientSync: ...
    @staticmethod
    def connect_network(network: Network | None = None) -> ClientSync: ...
    @staticmethod
    def from_config() -> ClientSync: ...
    @property
    def endpoint(self) -> str: ...
    @property
    def network(self) -> Network: ...
    def set_dry_run(self, enabled: bool) -> None: ...
    def is_dry_run(self) -> bool: ...
    def set_finalization_timeout(self, timeout: int) -> None: ...
    def finalization_timeout(self) -> int: ...
    def set_mortality_blocks(self, blocks: int) -> None: ...
    def mortality_blocks(self) -> int: ...
    def reconnect(self) -> None: ...
    def is_alive(self) -> bool: ...
    def invalidate_cache(self) -> None: ...
    def get_balance(self, address: str) -> Balance: ...
    def get_total_issuance(self) -> Balance: ...
    def get_metagraph(self, netuid: NetUid | int) -> dict[str, Any]: ...
    def __getattr__(self, name: str) -> Any: ...

class Wallet:
    @staticmethod
    def open(path: str) -> Wallet: ...
    @staticmethod
    def create(
        wallet_dir: str,
        name: str,
        password: str,
        hotkey_name: str = "default",
    ) -> tuple[Wallet, str, str]: ...
    @staticmethod
    def import_from_mnemonic(
        wallet_dir: str,
        name: str,
        mnemonic: str,
        password: str,
    ) -> Wallet: ...
    @staticmethod
    def create_from_uri(wallet_dir: str, uri: str, password: str) -> Wallet: ...
    @staticmethod
    def list_wallets(wallet_dir: str) -> list[str]: ...
    def unlock_coldkey(self, password: str) -> None: ...
    def load_hotkey(self, hotkey_name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def coldkey_ss58(self) -> str | None: ...
    @property
    def coldkey_public_ss58(self) -> str | None: ...
    @property
    def hotkey_ss58(self) -> str | None: ...
    def list_hotkeys(self) -> list[str]: ...
    def sign_message(self, role: str, message: bytes) -> bytes: ...
    @staticmethod
    def verify_message(ss58: str, message: bytes, signature: bytes) -> bool: ...

def raise_test_error(message: str) -> None: ...
