"""Type stubs for the native extension module."""

from typing import Any

class AgcliError(Exception):
    code: int
    hint: str | None

class Balance:
    def __init__(self, *, rao: int | None = None, tao: float | None = None) -> None: ...
    @staticmethod
    def from_rao(rao: int) -> Balance: ...
    @staticmethod
    def from_tao(tao: float) -> Balance: ...
    @property
    def rao(self) -> int: ...
    @property
    def tao(self) -> float: ...

class NetUid:
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...

class Network:
    @staticmethod
    def finney() -> Network: ...
    @staticmethod
    def test() -> Network: ...
    @staticmethod
    def local() -> Network: ...
    @staticmethod
    def archive() -> Network: ...
    @staticmethod
    def custom(url: str) -> Network: ...
    @staticmethod
    def parse(name: str) -> Network: ...
    @property
    def ws_url(self) -> str: ...

class Client:
    @staticmethod
    async def connect(url: str) -> Client: ...
    @staticmethod
    async def connect_with_retry(urls: list[str]) -> Client: ...
    @staticmethod
    async def connect_network(network: Network | None = None) -> Client: ...
    @staticmethod
    async def from_config() -> Client: ...
    @property
    def endpoint(self) -> str: ...
    async def get_balance(self, address: str) -> Balance: ...
    async def get_all_subnets(self) -> list[dict[str, Any]]: ...
    async def get_subnet_info(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_subnet_hyperparams(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_dynamic_info(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_metagraph(self, netuid: NetUid | int) -> dict[str, Any]: ...
    async def get_neuron(self, netuid: NetUid | int, uid: int) -> dict[str, Any] | None: ...
    async def get_neurons_lite(self, netuid: NetUid | int) -> list[dict[str, Any]]: ...
    async def get_stake_for_coldkey(self, coldkey: str) -> list[dict[str, Any]]: ...
    async def get_delegates(self) -> list[dict[str, Any]]: ...
    async def get_delegate(self, hotkey: str) -> dict[str, Any] | None: ...
    async def get_identity(self, ss58: str) -> dict[str, Any] | None: ...
    async def get_subnet_identity(self, netuid: NetUid | int) -> dict[str, Any] | None: ...

class Wallet:
    @staticmethod
    def open(path: str) -> Wallet: ...
    @staticmethod
    def create(
        wallet_dir: str,
        name: str,
        password: str,
        hotkey_name: str = "default",
    ) -> tuple[Wallet, str, str]: ...
    @staticmethod
    def import_from_mnemonic(
        wallet_dir: str,
        name: str,
        mnemonic: str,
        password: str,
    ) -> Wallet: ...
    @staticmethod
    def list_wallets(wallet_dir: str) -> list[str]: ...
    def unlock_coldkey(self, password: str) -> None: ...
    def load_hotkey(self, hotkey_name: str) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def coldkey_ss58(self) -> str | None: ...
    @property
    def hotkey_ss58(self) -> str | None: ...
    def list_hotkeys(self) -> list[str]: ...
