"""Type stubs for the native extension module."""

from typing import Any

HashInput = bytes | str

class AgcliError(Exception):
    code: int
    hint: str | None

class NetworkError(AgcliError): ...
class AuthError(AgcliError): ...
class ValidationError(AgcliError): ...
class ChainError(AgcliError): ...
class TimeoutError(AgcliError): ...
class IOError(AgcliError): ...

class Balance:
    def __init__(self, *, rao: int | None = None, tao: float | None = None) -> None: ...
    @staticmethod
    def from_rao(rao: int) -> Balance: ...
    @staticmethod
    def from_tao(tao: float) -> Balance: ...
    @property
    def rao(self) -> int: ...
    @property
    def tao(self) -> float: ...

class AlphaBalance:
    def __init__(self, value: Any) -> None: ...
    @property
    def raw(self) -> int: ...
    @property
    def rao(self) -> int: ...
    @property
    def tao(self) -> float: ...
    def to_dict(self) -> dict[str, Any]: ...

class NetUid:
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...

class Network:
    @staticmethod
    def finney() -> Network: ...
    @staticmethod
    def test() -> Network: ...
    @staticmethod
    def local() -> Network: ...
    @staticmethod
    def archive() -> Network: ...
    @staticmethod
    def custom(url: str) -> Network: ...
    @staticmethod
    def parse(name: str) -> Network: ...
    @property
    def ws_url(self) -> str: ...

class _TypedSerde:
    def __init__(self, value: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class SubnetInfo(_TypedSerde): ...
class NeuronInfo(_TypedSerde): ...
class NeuronInfoLite(_TypedSerde): ...
class Metagraph(_TypedSerde): ...
class StakeInfo(_TypedSerde): ...
class DelegateInfo(_TypedSerde): ...
class DynamicInfo(_TypedSerde): ...
class SubnetHyperparameters(_TypedSerde): ...
class ChainIdentity(_TypedSerde): ...
class SubnetIdentity(_TypedSerde): ...

class Config:
    network: str | None
    endpoint: str | None
    wallet_dir: str | None
    wallet: str | None
    hotkey: str | None
    output: str | None
    proxy: str | None
    live_interval: int | None
    batch: bool | None
    spending_limits: dict[str, float] | None
    finalization_timeout: int | None
    mortality_blocks: int | None
    def __init__(
        self,
        network: str | None = None,
        endpoint: str | None = None,
        wallet_dir: str | None = None,
        wallet: str | None = None,
        hotkey: str | None = None,
        output: str | None = None,
        proxy: str | None = None,
        live_interval: int | None = None,
        batch: bool | None = None,
        spending_limits: dict[str, float] | None = None,
        finalization_timeout: int | None = None,
        mortality_blocks: int | None = None,
    ) -> None: ...
    @staticmethod
    def load() -> Config: ...
    @staticmethod
    def load_from(path: str) -> Config: ...
    @staticmethod
    def default_path() -> str: ...
    def save(self) -> None: ...
    def save_to(self, path: str) -> None: ...

class Client:
    @staticmethod
    async def connect(url: str) -> Client: ...
    @staticmethod
    async def connect_with_retry(urls: list[str]) -> Client: ...
    @staticmethod
    async def best_connection(urls: list[str]) -> Client: ...
    @staticmethod
    async def connect_network(network: Network | None = None) -> Client: ...
    @staticmethod
    async def from_config() -> Client: ...
    @property
    def endpoint(self) -> str: ...
    @property
    def network(self) -> Network: ...
    def set_dry_run(self, enabled: bool) -> None: ...
    def is_dry_run(self) -> bool: ...
    def set_finalization_timeout(self, timeout: int) -> None: ...
    def finalization_timeout(self) -> int: ...
    def set_mortality_blocks(self, blocks: int) -> None: ...
    def mortality_blocks(self) -> int: ...
    async def reconnect(self) -> None: ...
    async def is_alive(self) -> bool: ...
    async def invalidate_cache(self) -> None: ...
    async def get_balance(self, address: str) -> Balance: ...
    async def get_balance_at_hash(self, address: str, block_hash: HashInput) -> Balance: ...
    async def get_balance_at_block(self, address: str, block_number: int) -> Balance: ...
    async def get_balances_multi(self, addresses: list[str]) -> list[tuple[str, dict[str, Any]]]: ...
    async def get_block_hash(self, block_number: int) -> str: ...
    async def get_block_number(self) -> int: ...
    async def get_finalized_block_number(self) -> int: ...
    async def pin_latest_block(self) -> str: ...
    async def get_total_stake_at_block(self, block_number: int) -> Balance: ...
    async def get_block_header(self, block_hash: HashInput) -> tuple[int, str, str, str]: ...
    async def get_block_extrinsic_count(self, block_hash: HashInput) -> int: ...
    async def get_block_timestamp(self, block_hash: HashInput) -> int | None: ...
    async def get_total_issuance(self) -> Balance: ...
    async def get_total_stake(self) -> Balance: ...
    async def get_total_networks(self) -> int: ...
    async def get_block_emission(self) -> Balance: ...
    async def get_subnet_registration_cost(self) -> Balance: ...
    async def get_network_overview(self) -> tuple[int, dict[str, Any], int, dict[str, Any], dict[str, Any]]: ...
    async def get_total_issuance_at(self, block_hash: HashInput) -> Balance: ...
    async def get_total_stake_at(self, block_hash: HashInput) -> Balance: ...
    async def get_total_networks_at(self, block_hash: HashInput) -> int: ...
    async def get_block_emission_at(self, block_hash: HashInput) -> Balance: ...
    async def get_block_number_at(self, block_hash: HashInput) -> int: ...
    async def get_all_subnets(self) -> list[dict[str, Any]]: ...
    async def get_subnet_info(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_subnet_hyperparams(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_dynamic_info(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_all_dynamic_info(self) -> list[dict[str, Any]]: ...
    async def get_metagraph(self, netuid: NetUid | int) -> dict[str, Any]: ...
    async def get_neuron(self, netuid: NetUid | int, uid: int) -> dict[str, Any] | None: ...
    async def get_neurons_lite(self, netuid: NetUid | int) -> list[dict[str, Any]]: ...
    async def get_stake_for_coldkey(self, coldkey: str) -> list[dict[str, Any]]: ...
    async def get_delegates(self) -> list[dict[str, Any]]: ...
    async def get_delegate(self, hotkey: str) -> dict[str, Any] | None: ...
    async def get_identity(self, ss58: str) -> dict[str, Any] | None: ...
    async def get_subnet_identity(self, netuid: NetUid | int) -> dict[str, Any] | None: ...
    async def get_subnet_info_pinned(self, netuid: NetUid | int, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def get_subnet_hyperparams_pinned(self, netuid: NetUid | int, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def get_identity_pinned(self, ss58: str, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def get_subnet_identity_pinned(self, netuid: NetUid | int, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def get_delegate_pinned(self, hotkey: str, block_hash: HashInput) -> dict[str, Any] | None: ...
    async def list_proxies_pinned(self, ss58: str, block_hash: HashInput) -> list[tuple[str, str, int]]: ...
    async def get_coldkey_swap_scheduled_pinned(self, ss58: str, block_hash: HashInput) -> tuple[int, str] | None: ...
    async def get_child_keys_pinned(self, hotkey_ss58: str, netuid: NetUid | int, block_hash: HashInput) -> list[tuple[int, str]]: ...
    async def get_pending_child_keys_pinned(self, hotkey_ss58: str, netuid: NetUid | int, block_hash: HashInput) -> tuple[list[tuple[int, str]], int] | None: ...
    async def get_stake_for_coldkey_pinned(self, coldkey: str, block_hash: HashInput) -> list[dict[str, Any]]: ...
    async def get_stake_for_coldkey_at_block(self, coldkey: str, block_number: int) -> list[dict[str, Any]]: ...
    async def get_identity_at_block(self, ss58: str, block_number: int) -> dict[str, Any] | None: ...
    async def get_all_subnets_at_block(self, block_number: int) -> list[dict[str, Any]]: ...
    async def get_all_dynamic_info_at_block(self, block_number: int) -> list[dict[str, Any]]: ...
    async def get_dynamic_info_at_block(self, netuid: NetUid | int, block_number: int) -> dict[str, Any] | None: ...
    async def get_neurons_lite_at_block(self, netuid: NetUid | int, block_number: int) -> list[dict[str, Any]]: ...
    async def get_neuron_at_block(self, netuid: NetUid | int, uid: int, block_number: int) -> dict[str, Any] | None: ...
    async def get_delegates_at_block(self, block_number: int) -> list[dict[str, Any]]: ...
    async def get_total_issuance_at_block(self, block_number: int) -> Balance: ...
    async def list_proxies(self, ss58: str) -> list[tuple[str, str, int]]: ...
    async def list_multisig_pending(self, multisig_ss58: str) -> list[tuple[str, int, int, int, int]]: ...
    async def list_proxy_announcements(self, ss58: str) -> list[tuple[str, str, int]]: ...
    async def get_coldkey_swap_scheduled(self, ss58: str) -> tuple[int, str] | None: ...
    async def get_child_keys(self, hotkey_ss58: str, netuid: NetUid | int) -> list[tuple[int, str]]: ...
    async def get_parent_keys(self, hotkey_ss58: str, netuid: NetUid | int) -> list[tuple[int, str]]: ...
    async def get_pending_child_keys(self, hotkey_ss58: str, netuid: NetUid | int) -> tuple[list[tuple[int, str]], int] | None: ...
    async def get_delegated(self, hotkey_ss58: str) -> list[dict[str, Any]]: ...
    async def get_weight_commits(self, netuid: NetUid | int, hotkey_ss58: str) -> list[tuple[str, int, int, int]] | None: ...
    async def get_all_weight_commits(self, netuid: NetUid | int) -> list[tuple[str, list[tuple[str, int, int, int]]]]: ...
    async def get_reveal_period_epochs(self, netuid: NetUid | int) -> int: ...
    async def get_weights_for_uid(self, netuid: NetUid | int, uid: int) -> list[tuple[int, int]]: ...
    async def get_all_weights(self, netuid: NetUid | int) -> list[tuple[int, list[tuple[int, int]]]]: ...
    async def get_commit_reveal_weights_version(self) -> int: ...
    async def get_commitment(self, netuid: int, hotkey_ss58: str) -> tuple[int, list[str]] | None: ...
    async def get_all_commitments(self, netuid: int) -> list[tuple[str, int, list[str]]]: ...
    async def get_block_info_for_pow(self) -> tuple[int, str]: ...
    async def get_difficulty(self, netuid: NetUid | int) -> int: ...
    async def fetch_portfolio(self, coldkey_ss58: str) -> dict[str, Any]: ...
    async def transfer(self, wallet: Wallet, dest_ss58: str, amount: Balance | int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def transfer_all(self, wallet: Wallet, dest_ss58: str, keep_alive: bool = False, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def add_stake(self, wallet: Wallet, netuid: NetUid | int, amount: Balance | int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def remove_stake(self, wallet: Wallet, netuid: NetUid | int, amount: Balance | int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def add_stake_limit(self, wallet: Wallet, netuid: NetUid | int, amount: Balance | int, limit_price: int, allow_partial: bool = True, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def remove_stake_limit(self, wallet: Wallet, netuid: NetUid | int, amount: Balance | int, limit_price: int, allow_partial: bool = True, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def move_stake(self, wallet: Wallet, from_netuid: NetUid | int, to_netuid: NetUid | int, amount: Balance | int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def swap_stake(self, wallet: Wallet, from_netuid: NetUid | int, to_netuid: NetUid | int, amount: Balance | int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def swap_stake_limit(self, wallet: Wallet, from_netuid: NetUid | int, to_netuid: NetUid | int, amount: Balance | int, limit_price: int, allow_partial: bool = True, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def transfer_stake(self, wallet: Wallet, dest_ss58: str, from_netuid: NetUid | int, to_netuid: NetUid | int, amount: Balance | int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def unstake_all(self, wallet: Wallet, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def unstake_all_alpha(self, wallet: Wallet, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def recycle_alpha(self, wallet: Wallet, netuid: NetUid | int, amount: int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def burn_alpha(self, wallet: Wallet, netuid: NetUid | int, amount: int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def claim_root(self, wallet: Wallet, subnets: list[int], *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def set_weights(self, wallet: Wallet, netuid: NetUid | int, uids: list[int], values: list[int], version_key: int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def commit_weights(self, wallet: Wallet, netuid: NetUid | int, commit_hash: HashInput, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def reveal_weights(self, wallet: Wallet, netuid: NetUid | int, uids: list[int], values: list[int], salt: list[int], version_key: int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def register_network(self, wallet: Wallet, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def burned_register(self, wallet: Wallet, netuid: NetUid | int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def pow_register(self, wallet: Wallet, netuid: NetUid | int, block_number: int, nonce: int, work: HashInput, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def root_register(self, wallet: Wallet, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def dissolve_network(self, wallet: Wallet, netuid: NetUid | int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def add_proxy(self, wallet: Wallet, delegate_ss58: str, proxy_type: str, delay: int = 0, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def remove_proxy(self, wallet: Wallet, delegate_ss58: str, proxy_type: str, delay: int = 0, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def create_pure_proxy(self, wallet: Wallet, proxy_type: str, delay: int = 0, index: int = 0, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def kill_pure_proxy(self, wallet: Wallet, spawner_ss58: str, proxy_type: str, index: int, height: int, ext_index: int, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def try_associate_hotkey(self, wallet: Wallet, hotkey_ss58: str | None = None, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def schedule_swap_coldkey(self, wallet: Wallet, new_coldkey_ss58: str, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def swap_hotkey(self, wallet: Wallet, old_hotkey_ss58: str, new_hotkey_ss58: str, *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    async def set_subnet_identity(self, wallet: Wallet, netuid: NetUid | int, identity: SubnetIdentity | dict[str, Any], *, wait: bool = True, mev: bool = True, dry_run: bool = False, finalization_timeout: int | None = None, mortality_blocks: int | None = None) -> str: ...
    def subscribe_events(self, filter: Any = None) -> EventStream: ...
    def subscribe_events_filtered(self, filter: Any) -> EventStream: ...
    def subscribe_blocks(self) -> EventStream: ...

class ClientSync:
    @staticmethod
    def connect(url: str) -> ClientSync: ...
    @staticmethod
    def connect_with_retry(urls: list[str]) -> ClientSync: ...
    @staticmethod
    def best_connection(urls: list[str]) -> ClientSync: ...
    @staticmethod
    def connect_network(network: Network | None = None) -> ClientSync: ...
    @staticmethod
    def from_config() -> ClientSync: ...
    @property
    def endpoint(self) -> str: ...
    @property
    def network(self) -> Network: ...
    def set_dry_run(self, enabled: bool) -> None: ...
    def is_dry_run(self) -> bool: ...
    def set_finalization_timeout(self, timeout: int) -> None: ...
    def finalization_timeout(self) -> int: ...
    def set_mortality_blocks(self, blocks: int) -> None: ...
    def mortality_blocks(self) -> int: ...
    def reconnect(self) -> None: ...
    def is_alive(self) -> bool: ...
    def invalidate_cache(self) -> None: ...
    def get_balance(self, address: str) -> Balance: ...
    def get_total_issuance(self) -> Balance: ...
    def get_metagraph(self, netuid: NetUid | int) -> dict[str, Any]: ...
    def __getattr__(self, name: str) -> Any: ...

class Wallet:
    @staticmethod
    def open(path: str) -> Wallet: ...
    @staticmethod
    def create(
        wallet_dir: str,
        name: str,
        password: str,
        hotkey_name: str = "default",
    ) -> tuple[Wallet, str, str]: ...
    @staticmethod
    def import_from_mnemonic(
        wallet_dir: str,
        name: str,
        mnemonic: str,
        password: str,
    ) -> Wallet: ...
    @staticmethod
    def create_from_uri(wallet_dir: str, uri: str, password: str) -> Wallet: ...
    @staticmethod
    def list_wallets(wallet_dir: str) -> list[str]: ...
    def unlock_coldkey(self, password: str) -> None: ...
    def unlock_coldkey_with_password(self, password: str) -> None: ...
    def load_hotkey(self, hotkey_name: str) -> None: ...
    def lock(self) -> None: ...
    @property
    def is_coldkey_unlocked(self) -> bool: ...
    @property
    def is_hotkey_loaded(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def coldkey_ss58(self) -> str | None: ...
    @property
    def coldkey_public_ss58(self) -> str | None: ...
    @property
    def hotkey_ss58(self) -> str | None: ...
    def list_hotkeys(self) -> list[str]: ...
    def sign_message(self, role: str, message: bytes) -> bytes: ...
    @staticmethod
    def verify_message(ss58: str, message: bytes, signature: bytes) -> bool: ...

def raise_test_error(message: str) -> None: ...

class EventStream:
    def __aiter__(self) -> EventStream: ...
    async def __anext__(self) -> dict[str, Any]: ...
    async def close(self) -> None: ...

class LocalnetConfig:
    image: str
    container_name: str
    port: int
    wait: bool
    wait_timeout: int
    def __init__(
        self,
        image: str | None = None,
        container_name: str | None = None,
        port: int | None = None,
        wait: bool | None = None,
        wait_timeout: int | None = None,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class DevAccount:
    name: str
    uri: str
    ss58: str
    balance: str
    def to_dict(self) -> dict[str, Any]: ...

class LocalnetInfo:
    container_name: str
    container_id: str
    image: str
    endpoint: str
    port: int
    block_height: int
    dev_accounts: list[DevAccount]
    def to_dict(self) -> dict[str, Any]: ...

class LocalnetStatus:
    running: bool
    container_name: str
    container_id: str | None
    image: str | None
    endpoint: str | None
    block_height: int | None
    started_at: str | None
    uptime: str | None
    def to_dict(self) -> dict[str, Any]: ...

class NeuronConfig:
    name: str
    fund_tao: float | None
    register: bool
    def __init__(
        self, name: str, fund_tao: float | None = None, register: bool = True
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class SubnetConfig:
    tempo: int | None
    max_allowed_validators: int | None
    max_allowed_uids: int | None
    min_allowed_weights: int | None
    max_weight_limit: int | None
    immunity_period: int | None
    weights_rate_limit: int | None
    commit_reveal: bool | None
    activity_cutoff: int | None
    neurons: list[NeuronConfig]
    def __init__(
        self,
        tempo: int | None = None,
        max_allowed_validators: int | None = None,
        max_allowed_uids: int | None = None,
        min_allowed_weights: int | None = None,
        max_weight_limit: int | None = None,
        immunity_period: int | None = None,
        weights_rate_limit: int | None = None,
        commit_reveal: bool | None = None,
        activity_cutoff: int | None = None,
        neurons: list[NeuronConfig] | None = None,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class ChainConfig:
    image: str
    container: str
    port: int
    start: bool
    timeout: int
    def __init__(
        self,
        image: str | None = None,
        container: str | None = None,
        port: int | None = None,
        start: bool | None = None,
        timeout: int | None = None,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class ScaffoldConfig:
    chain: ChainConfig
    subnets: list[SubnetConfig]
    def __init__(
        self,
        chain: ChainConfig | None = None,
        subnets: list[SubnetConfig] | None = None,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class NeuronResult:
    name: str
    ss58: str
    seed: str
    uid: int | None
    balance_tao: float | None
    def to_dict(self) -> dict[str, Any]: ...

class SubnetResult:
    netuid: int
    hyperparams: dict[str, Any]
    neurons: list[NeuronResult]
    def to_dict(self) -> dict[str, Any]: ...

class ScaffoldResult:
    endpoint: str
    container: str | None
    block_height: int
    subnets: list[SubnetResult]
    def to_dict(self) -> dict[str, Any]: ...

class _LiveModule:
    @staticmethod
    async def live_dynamic(client: Client, interval_secs: int = 5) -> None: ...
    @staticmethod
    async def live_metagraph(
        client: Client, netuid: NetUid | int, interval_secs: int = 5
    ) -> None: ...
    @staticmethod
    async def live_portfolio(
        client: Client, coldkey_ss58: str, interval_secs: int = 5
    ) -> None: ...

class _LocalnetModule:
    DEFAULT_IMAGE: str
    DEFAULT_CONTAINER: str
    DEFAULT_WS: str
    @staticmethod
    def dev_accounts() -> list[DevAccount]: ...
    @staticmethod
    async def start(config: LocalnetConfig | None = None) -> LocalnetInfo: ...
    @staticmethod
    def stop(container_name: str) -> None: ...
    @staticmethod
    async def status(
        container_name: str | None = None, port: int = 9944
    ) -> LocalnetStatus: ...
    @staticmethod
    async def reset(config: LocalnetConfig | None = None) -> LocalnetInfo: ...
    @staticmethod
    def logs(container_name: str, tail: int | None = None) -> str: ...

class _ScaffoldModule:
    @staticmethod
    def load_config(path: str) -> ScaffoldConfig: ...
    @staticmethod
    async def run(config: ScaffoldConfig) -> ScaffoldResult: ...

class _AdminModule:
    @staticmethod
    def known_params() -> list[tuple[str, str, list[str]]]: ...
    @staticmethod
    async def raw_admin_call(client: Client, wallet: Wallet, call_name: str, args: list[Any]) -> str: ...
    @staticmethod
    async def set_tempo(client: Client, wallet: Wallet, netuid: NetUid | int, tempo: int) -> str: ...
    @staticmethod
    async def set_max_allowed_validators(client: Client, wallet: Wallet, netuid: NetUid | int, max: int) -> str: ...
    @staticmethod
    async def set_max_allowed_uids(client: Client, wallet: Wallet, netuid: NetUid | int, max: int) -> str: ...
    @staticmethod
    async def set_immunity_period(client: Client, wallet: Wallet, netuid: NetUid | int, period: int) -> str: ...
    @staticmethod
    async def set_min_allowed_weights(client: Client, wallet: Wallet, netuid: NetUid | int, min: int) -> str: ...
    @staticmethod
    async def set_max_weight_limit(client: Client, wallet: Wallet, netuid: NetUid | int, limit: int) -> str: ...
    @staticmethod
    async def set_weights_set_rate_limit(client: Client, wallet: Wallet, netuid: NetUid | int, limit: int) -> str: ...
    @staticmethod
    async def set_commit_reveal_weights_enabled(client: Client, wallet: Wallet, netuid: NetUid | int, enabled: bool) -> str: ...
    @staticmethod
    async def set_difficulty(client: Client, wallet: Wallet, netuid: NetUid | int, difficulty: int) -> str: ...
    @staticmethod
    async def set_bonds_moving_average(client: Client, wallet: Wallet, netuid: NetUid | int, avg: int) -> str: ...
    @staticmethod
    async def set_target_registrations_per_interval(client: Client, wallet: Wallet, netuid: NetUid | int, target: int) -> str: ...
    @staticmethod
    async def set_activity_cutoff(client: Client, wallet: Wallet, netuid: NetUid | int, cutoff: int) -> str: ...
    @staticmethod
    async def set_serving_rate_limit(client: Client, wallet: Wallet, netuid: NetUid | int, limit: int) -> str: ...
    @staticmethod
    async def set_default_take(client: Client, wallet: Wallet, take: int) -> str: ...
    @staticmethod
    async def set_tx_rate_limit(client: Client, wallet: Wallet, limit: int) -> str: ...
    @staticmethod
    async def set_min_difficulty(client: Client, wallet: Wallet, netuid: NetUid | int, min: int) -> str: ...
    @staticmethod
    async def set_max_difficulty(client: Client, wallet: Wallet, netuid: NetUid | int, max: int) -> str: ...
    @staticmethod
    async def set_adjustment_interval(client: Client, wallet: Wallet, netuid: NetUid | int, interval: int) -> str: ...
    @staticmethod
    async def set_adjustment_alpha(client: Client, wallet: Wallet, netuid: NetUid | int, alpha: int) -> str: ...
    @staticmethod
    async def set_kappa(client: Client, wallet: Wallet, netuid: NetUid | int, kappa: int) -> str: ...
    @staticmethod
    async def set_rho(client: Client, wallet: Wallet, netuid: NetUid | int, rho: int) -> str: ...
    @staticmethod
    async def set_min_burn(client: Client, wallet: Wallet, netuid: NetUid | int, min_burn: int) -> str: ...
    @staticmethod
    async def set_max_burn(client: Client, wallet: Wallet, netuid: NetUid | int, max_burn: int) -> str: ...
    @staticmethod
    async def set_liquid_alpha_enabled(client: Client, wallet: Wallet, netuid: NetUid | int, enabled: bool) -> str: ...
    @staticmethod
    async def set_alpha_values(client: Client, wallet: Wallet, netuid: NetUid | int, alpha_low: int, alpha_high: int) -> str: ...
    @staticmethod
    async def set_yuma3_enabled(client: Client, wallet: Wallet, netuid: NetUid | int, enabled: bool) -> str: ...
    @staticmethod
    async def set_bonds_penalty(client: Client, wallet: Wallet, netuid: NetUid | int, penalty: int) -> str: ...
    @staticmethod
    async def set_subnet_moving_alpha(client: Client, wallet: Wallet, alpha: int) -> str: ...
    @staticmethod
    async def set_mechanism_count(client: Client, wallet: Wallet, netuid: NetUid | int, count: int) -> str: ...
    @staticmethod
    async def set_mechanism_emission_split(client: Client, wallet: Wallet, netuid: NetUid | int, split: list[int]) -> str: ...
    @staticmethod
    async def set_stake_threshold(client: Client, wallet: Wallet, threshold: int) -> str: ...
    @staticmethod
    async def set_nominator_min_required_stake(client: Client, wallet: Wallet, min_stake: int) -> str: ...
    @staticmethod
    async def set_network_registration_allowed(client: Client, wallet: Wallet, netuid: NetUid | int, allowed: bool) -> str: ...
    @staticmethod
    async def set_network_pow_registration_allowed(client: Client, wallet: Wallet, netuid: NetUid | int, allowed: bool) -> str: ...

live: _LiveModule
localnet: _LocalnetModule
scaffold: _ScaffoldModule
admin: _AdminModule
